name: Cleanup ghcr.io images

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Dry run
        type: boolean
        required: true
        default: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f
        with:
          dry-run: ${{ inputs.dry_run }}
