name: Publish ministatus to PyPI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'
          enable-cache: true
      - run: uv build
      - uses: actions/upload-artifact@v5
        with:
          name: dist-${{ runner.os }}
          path: dist/

  publish:
    environment: pypi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs:
      - build

    steps:
      - uses: actions/download-artifact@v6
        with:
          pattern: dist-*
          path: dist/
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@v1.13.0
