name: Lint with Pyright

on:
  push:
    paths:
      - '**.py'
      - pyproject.toml
      - uv.lock
  pull_request:
    paths:
      - '**.py'
      - pyproject.toml
      - uv.lock

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: '3.11'
          enable-cache: true
      - run: uv sync --locked --all-extras --dev
      - run: uvx pyright --pythonpath .venv/bin/python
